# We are going to make our first Flask application with Python
# Let's verify Python is working on this machine

from flask import Flask

# need to create an instance of the Flask class
app = Flask(__name__)

# need to create a route that will be the main page of the application. 
# A route is a URL that the application will respond to the client browser request

# We are going to use a route decorator to create a route.
@app.route('/') 
def index():
    # Whatever we return from this function will be displayed in the browser. 
    return 'I was dynamically generated by a developer!'


# Start the application
# This is the entry point of the application for Python
if __name__ == "__main__":
    # NOw we get to start the Flask application server. 
    # Listen for incoming requests from the client browser. 
    # If no errors, this will keep running until we stop it.
    app.run()