# We are going to make our first Flask application with Python
# Let's verify Python is working on this machine

from flask import Flask, send_file, render_template_string

# need to create an instance of the Flask class
app = Flask(__name__)

# need to create a route that will be the main page of the application. 
# A route is a URL that the application will respond to the client browser request

# We are going to use a route decorator to create a route.
@app.route('/') 
def index():
    # Whatever we return from this function will be displayed in the browser. 
    return "<h1>I was dynamically generated by a developer!</h1><p>This is my first Flask app</p>"


@app.route('/greet/<name>')
def greet(name):
    return f"<h1>Greetings {name}</h1><p> So glad to see you here today!</p>"


# Route to read and download short story
@app.route('/download_zavala')
def download_zavala():
    # create a path to the file
    file_path = "zavala.txt"
    
    #send file to client browser to download
    return send_file(file_path, as_attachment=True)


# Let's create a route to display download link for the story. 
@app.route('/read_zavala')
def read_zavala():
    # Create a html template that will display the download link
    html_content = """
    <h1> Download the story Zavala</h1>
    <p> click the link below to download the story</p>
    <a href="/download_zavala"> Download Zavala short story</a>
    """

    # Now we send the HTML template to the client browser
    return render_template_string(html_content)

@app.route('/landing_page')
def landing_page():
    html_content = """
    <!DOCTYPE html>
    <html>
        <head>
            <title>Test</title>
        </head>
        <body style="background-image: url('{{'static', filename='static/wq_media_wallpaper_1.jpg')}}')">
            <header style="text-align: center;">
                <h1>Destiny 2 is a great game</h1>
                <p>Can't wait for the next DLC!</p>
            </header>
        </body>
    </html>
    """
    return render_template_string(html_content)



# Start the application
# This is the entry point of the application for Python
if __name__ == "__main__":
    # Now we get to start the Flask application server. 
    # Listen for incoming requests from the client browser. 
    # If no errors, this will keep running until we stop it.
    app.run()